### ISSUE TITLE
Lib crashes continue with some phones

### ISSUE THREAD

**Issue by cedricf25** [mroczis/netmonster-core#12]
Lib crashes continue :

Fatal Exception: java.lang.IllegalStateException: Pid 16907 has exceeded the number of permissible registered listeners. Ignoring request to add.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:1105)
       at android.telephony.TelephonyRegistryManager.listenForSubscriber(TelephonyRegistryManager.java:231)
       at android.telephony.TelephonyManager.listen(TelephonyManager.java:6706)
       at cz.mroczis.netmonster.core.feature.config.TelephonyManagerListenersKt$requestSingleUpdate$1.run(TelephonyManagerListeners.kt:60)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by mroczis** [comment]
Can you describe the problem more precisely? Which devices are affected? Does this problem appear every time after NTM core is used or after some fixed period of time? Do you invoke call to NTM core library from fixed thread or each time from different ones?

**Comment by cedricf25** [comment]
The bug from firebase crashlitics affects:
- 49% samsung (Galaxy S10+, Galaxy Note 10 Lite, Galaxy S10e, ...)
- 27% OnePlus (KB2003, GM1900, ..)
- 11% Xiaomi (mi 11, Mi10Lite 5G, Mi 9 SE, ..)
- 7% Google (Pixel 4, Pixel 4a, Pixel 5, ..)
- ...

Android 10 (6%) and Android 11 (94%)

The problem append after some period of time. I invoke core library at fixed rate every 3 seconds. It's too much? Is there a method that free the listeners ?

Thank you mroczis :)

**Comment by xcadrik** [comment]
I have experienced the issue too (Samsung Galaxy A51, android 11, forced to use 2G network - interesting is that for 4G and 3G it was ok, but for 2G it delivers a lot of cells (around 20), maybe its processing time causes trouble in higher refresh rate) and I was able to fix it by https://github.com/mroczis/netmonster-core/pull/23/commits, but I am not sure if it is 100% correct solution. At least app is not crashing and information is delivered. I use 1s refreh rate of the information from getCells() and from various threads. (I was not able to reproduce it in library sample project)

**Comment by mroczis** [comment]
Thanks to help from @xcadrik I managed to identify the root cause. The problem is basically that you are making way too many requests to the library which then delegates them to the system. Since Android P, there's a limit of max 50 parallel registered instances of `PhoneStateListener`. I'd strongly advise you to deal better with threading. However, fix is also coming to the library.

From now on such data will be cached for 1 second to avoid excessive calls.
